# Generated by Django 5.2 on 2025-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
